# Generated by Django 5.1.4 on 2024-12-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_realtor_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('avadi', 'Avadi'), ('ambattur', 'Ambattur'), ('thirumullaivoyal', 'Thirumullaivoyal'), ('redhills', 'Redhills'), ('tiruvallur', 'Tiruvallur')], max_length=50),
        ),
    ]
